POPERTY_KEY = "property_name"
OPEN_WINDOW_ACTION = "open_window"
FILE_FORMAT = "JSON (*.json);;"
BSDD_PATH = "bsdd_export"
LANGUAGE_ISO_CODES = [
    "EN",
    "en-GB",
    "nl-NL",
    "nb-NO",
    "nl-BE",
    "fr-BE",
    "de-DE",
    "it-IT",
    "sv-SE",
    "fr-FR",
    "es-ES",
    "en-AU",
    "fa-IR",
    "pl-PL",
    "lv-LV",
    "en-NZ",
    "sr-SP",
    "zh-CN",
    "ru-RU",
    "vi-VN",
    "bg-BG",
    "kr-KR",
    "ar-SA",
    "el-GR",
    "de-AT",
    "mn-MN",
    "en-CA",
    "lt-LT",
    "da-DK",
    "de-CH",
    "et-EE",
    "cs-CZ",
    "nn-NO",
    "en-US",
    "pt-BR",
    "fi-FI",
    "ja-JP",
    "no-NO",
    "pt-PT",
]
