SEPERATOR_SECTION = "property_set_window"
SEPERATOR_STATUS = "seperator_status"
SEPERATOR = "seperator"
ALLOWED_UNITS = "allowed_units"
UNITS_SECTION = "property_set_window"
ALLOWED_PREFIXES = "allowed_prefixes"